create table stock_monthly_summary_flatten as (
select yearmonthstr, 
max(ascott_month_open) as ascott_month_open, 
max(ascott_month_close) as ascott_month_close,
max(ascott_month_trend) as ascott_month_trend, 
max(genting_month_open) as genting_month_open, 
max(genting_month_close) as genting_month_close,
max(genting_month_trend) as genting_month_trend, 
max(hotel_prop_month_open) as hotel_prop_month_open, 
max(hotel_prop_month_close) as hotel_prop_month_close,
max(hotel_prop_month_trend) as hotel_prop_month_trend, 
max(mandarin_month_open) as mandarin_month_open, 
max(mandarin_month_close) as mandarin_month_close,
max(mandarin_month_trend) as mandarin_month_trend, 
max(singair_month_open) as singair_month_open, 
max(singair_month_close) as singair_month_close,
max(singair_month_trend) as singair_month_trend 
from (
 select 
 yearmonthstr,
 case when stock_name = 'Ascott Residence Trust' then month_open else 0 end as ascott_month_open,
 case when stock_name = 'Ascott Residence Trust' then month_close else 0 end as ascott_month_close,
 case when stock_name = 'Ascott Residence Trust' then trend else '' end as ascott_month_trend,
  case when stock_name = 'Genting Singapore' then month_open else 0 end as genting_month_open,
 case when stock_name = 'Genting Singapore' then month_close else 0 end as genting_month_close,
 case when stock_name = 'Genting Singapore' then trend else '' end as genting_month_trend,
  case when stock_name = 'Hotel Properties' then month_open else 0 end as hotel_prop_month_open,
 case when stock_name = 'Hotel Properties' then month_close else 0 end as hotel_prop_month_close,
 case when stock_name = 'Hotel Propertiest' then trend else '' end as hotel_prop_month_trend,
  case when stock_name = 'Mandarin Oriental' then month_open else 0 end as mandarin_month_open,
 case when stock_name = 'Mandarin Oriental' then month_close else 0 end as mandarin_month_close,
 case when stock_name = 'Mandarin Oriental' then trend else '' end as mandarin_month_trend,
  case when stock_name = 'Singapore Airlines' then month_open else 0 end as singair_month_open,
 case when stock_name = 'Singapore Airlines' then month_close else 0 end as singair_month_close,
 case when stock_name = 'Singapore Airlines' then trend else '' end as singair_month_trend
 from stock_monthly_summary) temp
 group by yearmonthstr);


 select * from stock_monthly_summary_flatten;
 
 
 create table singapore_tourist_arrival (
month varchar , 
Total_International int ,     
     Southeast_Asia int,
         Brunei int ,
         Indonesia int,
         Malaysia int,         
         Myanmar  int,
         Philippines  int,
         Thailand  int,
         Vietm  int,
         Other_Southeast_Asia  int,
     Greater_China  int,
         Chi  int,
         Hong_Kong_SAR  int,
         Taiwan  int,
         Other_Greater_China  int,
     North_Asia  int,
         Japan  int,
         South_Korea  int,
         Other_North_Asia  int,
     South_Asia  int,
         Bangladesh  int,
         India  int,
         Pakistan  int,
         Sri_Lanka  int,
         Other_South_Asia  int,
     West_Asia  int,
         Iran  int,
         Israel  int,
         Kuwait  int,
         Saudi_Arabia  int,
         United_Arab_Emirates  int,
         Other_West_Asia  int,
     Americas  int,
         Canada  int,
         USA  int,
         Other_Americas  int,
     Europe  int,
         Belgium_Luxembourg  int,
         Denmark  int,
         Finland  int,
         France  int,
         Germany  int,
         Italy  int,
         Netherlands  int,
         Norway  int,
         Rep_Of_Ireland  int,
         Russian  int,
         Spain  int,
         Sweden  int,
         Switzerland  int,
         United_Kingdom  int,
         Other_Europe  int,
     Oceania  int,
         Australia  int,
         New_Zealand  int,
         Other_Oceania  int,
     Africa  int,
         Egypt  int,
         Mauritius  int,
         South_Africa int,
         Other_Africa  int,
     Others int)

select * from datamining.singapore_tourist_arrival;