select * from datamining.singapore_haze_psi_by_month;

-- 200901 - 201910

select * from datamining.singapore_top5_tourism_stock_data_by_month_flatten
-- 200901 - 201910

select * from datamining.singapore_tourist_arrival;
-- 197801 - 201907

select * from datamining.singapore_haze_psi_by_month psi,
datamining.singapore_top5_tourism_stock_data_by_month_flatten stock,
datamining.singapore_tourist_arrival tourist
where psi.month = stock.month 
and psi.month = tourist.month;


create table datamining.singapore_tourist_haze_psi as
select psi.month as month,
psi.min_westpsi,
psi.max_westpsi,
psi.avg_westpsi,
psi.min_eastpsi,
psi.max_eastpsi,
psi.avg_eastpsi,
psi.min_centralpsi,
psi.max_centralpsi,
psi.avg_centralpsi,
psi.min_southpsi,
psi.max_southpsi,
psi.avg_southpsi,
psi.min_northpsi,
psi.max_northpsi,
psi.avg_northpsi,
stock.singapore_airlines_min_open,
stock.singapore_airlines_max_open,
stock.singapore_airlines_avg_open,
stock.singapore_airlines_min_high,
stock.singapore_airlines_max_high,
stock.singapore_airlines_avg_high,
stock.singapore_airlines_min_low,
stock.singapore_airlines_max_low,
stock.singapore_airlines_avg_low,
stock.singapore_airlines_min_adj_close,
stock.singapore_airlines_max_adj_close,
stock.singapore_airlines_avg_adj_close,
stock.singapore_airlines_min_volume,
stock.singapore_airlines_max_volume,
stock.singapore_airlines_avg_volume,
stock.mandarin_oriental_min_open,
stock.mandarin_oriental_max_open,
stock.mandarin_oriental_avg_open,
stock.mandarin_oriental_min_high,
stock.mandarin_oriental_max_high,
stock.mandarin_oriental_avg_high,
stock.mandarin_oriental_min_low,
stock.mandarin_oriental_max_low,
stock.mandarin_oriental_avg_low,
stock.mandarin_oriental_min_adj_close,
stock.mandarin_oriental_max_adj_close,
stock.mandarin_oriental_avg_adj_close,
stock.mandarin_oriental_min_volume,
stock.mandarin_oriental_max_volume,
stock.mandarin_oriental_avg_volume,
stock.hotel_properties_min_open,
stock.hotel_properties_max_open,
stock.hotel_properties_avg_open,
stock.hotel_properties_min_high,
stock.hotel_properties_max_high,
stock.hotel_properties_avg_high,
stock.hotel_properties_min_low,
stock.hotel_properties_max_low,
stock.hotel_properties_avg_low,
stock.hotel_properties_min_adj_close,
stock.hotel_properties_max_adj_close,
stock.hotel_properties_avg_adj_close,
stock.hotel_properties_min_volume,
stock.hotel_properties_max_volume,
stock.hotel_properties_avg_volume,
stock.genting_singapore_min_open,
stock.genting_singapore_max_open,
stock.genting_singapore_avg_open,
stock.genting_singapore_min_high,
stock.genting_singapore_max_high,
stock.genting_singapore_avg_high,
stock.genting_singapore_min_low,
stock.genting_singapore_max_low,
stock.genting_singapore_avg_low,
stock.genting_singapore_min_adj_close,
stock.genting_singapore_max_adj_close,
stock.genting_singapore_avg_adj_close,
stock.genting_singapore_min_volume,
stock.genting_singapore_max_volume,
stock.genting_singapore_avg_volume,
stock.ascott_residence_trust_min_open,
stock.ascott_residence_trust_max_open,
stock.ascott_residence_trust_avg_open,
stock.ascott_residence_trust_min_high,
stock.ascott_residence_trust_max_high,
stock.ascott_residence_trust_avg_high,
stock.ascott_residence_trust_min_low,
stock.ascott_residence_trust_max_low,
stock.ascott_residence_trust_avg_low,
stock.ascott_residence_trust_min_adj_close,
stock.ascott_residence_trust_max_adj_close,
stock.ascott_residence_trust_avg_adj_close,
stock.ascott_residence_trust_min_volume,
stock.ascott_residence_trust_max_volume,
stock.ascott_residence_trust_avg_volume,
tourist.total_international,
tourist.southeast_asia,
tourist.brunei,
tourist.indonesia,
tourist.malaysia,
tourist.myanmar,
tourist.philippines,
tourist.thailand,
tourist.vietm,
tourist.other_southeast_asia,
tourist.greater_china,
tourist.chi,
tourist.hong_kong_sar,
tourist.taiwan,
tourist.other_greater_china,
tourist.north_asia,
tourist.japan,
tourist.south_korea,
tourist.other_north_asia,
tourist.south_asia,
tourist.bangladesh,
tourist.india,
tourist.pakistan,
tourist.sri_lanka,
tourist.other_south_asia,
tourist.west_asia,
tourist.iran,
tourist.israel,
tourist.kuwait,
tourist.saudi_arabia,
tourist.united_arab_emirates,
tourist.other_west_asia,
tourist.americas,
tourist.canada,
tourist.usa,
tourist.other_americas,
tourist.europe,
tourist.belgium_luxembourg,
tourist.denmark,
tourist.finland,
tourist.france,
tourist.germany,
tourist.italy,
tourist.netherlands,
tourist.norway,
tourist.rep_of_ireland,
tourist.russian,
tourist.spain,
tourist.sweden,
tourist.switzerland,
tourist.united_kingdom,
tourist.other_europe,
tourist.oceania,
tourist.australia,
tourist.new_zealand,
tourist.other_oceania,
tourist.africa,
tourist.egypt,
tourist.mauritius,
tourist.south_africa,
tourist.other_africa,
tourist.others
from datamining.singapore_haze_psi_by_month psi
join datamining.singapore_top5_tourism_stock_data_by_month_flatten stock 
	on psi.month = stock.month 
left outer join datamining.singapore_tourist_arrival tourist 
	on psi.month = tourist.month;


	select * from datamining.singapore_tourist_haze_psi;